/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;

public class App {


    public static void main(String[] args) {

        Gson gson = new Gson();
        File files=new File("jsonFile");
//        for (file:
//
//              {
//
//        }
//        Contain ahmadObj = gson.fromJson(String.valueOf(files), Contain.class);

    }
}
